import type { AppMenuRecord } from '@/menu/types';

export const blogSurferMenus: AppMenuRecord[] = [
  {
    id: 'blog-surfer_home',
    parentId: null,
    menuType: 'route',
    routerName: 'blog-surfer_home',
    path: '/blog/surfer/home',
    tableName: 'blog-surfer_home',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_home',
    icon: 'mdi:home-outline',
    order: 1
  },
  {
    id: 'blog-surfer_content',
    parentId: null,
    menuType: 'folder',
    path: '/blog/surfer/content',
    tableName: '.',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_content',
    icon: 'mdi:book-open-page-variant-outline',
    order: 3
  },
  {
    id: 'blog-surfer_dashboard',
    parentId: 'blog-surfer_content',
    menuType: 'route',
    routerName: 'blog-surfer_dashboard',
    path: '/blog/surfer/dashboard',
    tableName: 'blog-surfer_dashboard',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_dashboard',
    icon: 'mdi:view-dashboard-outline',
    order: 1
  },
  {
    id: 'blog-surfer_column',
    parentId: null,
    menuType: 'route',
    routerName: 'blog-surfer_column',
    path: '/blog/surfer/column',
    tableName: 'blog-surfer_column',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_column',
    icon: 'mdi:bookshelf',
    order: 2
  },
  {
    id: 'blog-surfer_archive',
    parentId: 'blog-surfer_content',
    menuType: 'route',
    routerName: 'blog-surfer_archive',
    path: '/blog/surfer/archive',
    tableName: 'blog-surfer_archive',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_archive',
    icon: 'mdi:archive-outline',
    order: 3
  },
  {
    id: 'blog-surfer_category',
    parentId: 'blog-surfer_content',
    menuType: 'route',
    routerName: 'blog-surfer_category',
    path: '/blog/surfer/category',
    tableName: 'blog-surfer_category',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_category',
    icon: 'mdi:shape-outline',
    order: 4
  },
  {
    id: 'blog-surfer_tag',
    parentId: 'blog-surfer_content',
    menuType: 'route',
    routerName: 'blog-surfer_tag',
    path: '/blog/surfer/tag',
    tableName: 'blog-surfer_tag',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_tag',
    icon: 'mdi:tag-multiple-outline',
    order: 5
  },
  {
    id: 'blog-surfer_interaction',
    parentId: null,
    menuType: 'folder',
    path: '/blog/surfer/interaction',
    tableName: '.',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_interaction',
    icon: 'mdi:message-bulleted',
    order: 5
  },
  {
    id: 'blog-surfer_about',
    parentId: 'blog-surfer_interaction',
    menuType: 'route',
    routerName: 'blog-surfer_about',
    path: '/blog/surfer/about',
    tableName: 'blog-surfer_about',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_about',
    icon: 'mdi:information-outline',
    order: 1
  },
  {
    id: 'blog-surfer_author',
    parentId: 'blog-surfer_interaction',
    menuType: 'route',
    routerName: 'blog-surfer_author',
    path: '/blog/surfer/author',
    tableName: 'blog-surfer_author',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_author',
    icon: 'mdi:account-outline',
    order: 2
  },
  {
    id: 'blog-surfer_friend',
    parentId: 'blog-surfer_interaction',
    menuType: 'route',
    routerName: 'blog-surfer_friend',
    path: '/blog/surfer/friend',
    tableName: 'blog-surfer_friend',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_friend',
    icon: 'mdi:link-variant',
    order: 3
  },
  {
    id: 'blog-surfer_message',
    parentId: 'blog-surfer_interaction',
    menuType: 'route',
    routerName: 'blog-surfer_message',
    path: '/blog/surfer/message',
    tableName: 'blog-surfer_message',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_message',
    icon: 'mdi:message-outline',
    order: 4
  },
  {
    id: 'blog-surfer_more',
    parentId: null,
    menuType: 'folder',
    path: '/blog/surfer/more',
    tableName: '.',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_more',
    icon: 'mdi:dots-horizontal-circle-outline',
    order: 6
  },
  {
    id: 'blog-surfer_gallery',
    parentId: 'blog-surfer_more',
    menuType: 'route',
    routerName: 'blog-surfer_gallery',
    path: '/blog/surfer/gallery',
    tableName: 'blog-surfer_gallery',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_gallery',
    icon: 'mdi:wallpaper',
    order: 1
  },
  {
    id: 'blog-surfer_moments',
    parentId: 'blog-surfer_more',
    menuType: 'route',
    routerName: 'blog-surfer_moments',
    path: '/blog/surfer/moments',
    tableName: 'blog-surfer_moments',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_moments',
    icon: 'mdi:chat-outline',
    order: 2
  },
  {
    id: 'blog-surfer_equipment',
    parentId: 'blog-surfer_more',
    menuType: 'route',
    routerName: 'blog-surfer_equipment',
    path: '/blog/surfer/equipment',
    tableName: 'blog-surfer_equipment',
    enabled: true,
    menuI18nKey: 'route.blog-surfer_equipment',
    icon: 'mdi:monitor-cellphone',
    order: 3
  }
];
