namespace Mint.Blog.Application.Blog.Statistics.Queries.GetAdminDashboardPublishArticleStatistics;

public interface IGetAdminDashboardPublishArticleStatisticsQueryService {
	Task<AdminDashboardPublishArticleStatisticsDto> GetAsync(CancellationToken cancellationToken = default);
}